### ISSUE TITLE
Night Light not working

### ISSUE THREAD

**Issue by MartinFlischman** [elementary/switchboard-plug-display#250]
Night Light is not working at all. I have set my laptop to a manual time, sunset to sunrise, checked for any updates, restarted.....still nothing.

![Screenshot from 2020-07-15 05 36 27](https://user-images.githubusercontent.com/26260699/87500852-e2f22680-c65d-11ea-9ef9-c70487b238f0.png)
![Screenshot from 2020-07-15 05 36 53](https://user-images.githubusercontent.com/26260699/87500856-e5ed1700-c65d-11ea-86cc-d1526470cfc9.png)
![Screenshot from 2020-07-15 05 40 38](https://user-images.githubusercontent.com/26260699/87500857-e7b6da80-c65d-11ea-97e7-3b91adc2875f.png)

**Comment by cassidyjames** [comment]
@MartinFlischman hm, I have used it with a similar-specced laptop and not had issues. Is this reproducible for you on a fresh install/from the live image? Do you have anything that might be conflicting, trying to modify the display's color temperature? I've seen issues when trying to also use another display-related app, because then Night Light is unable to set the color temperature.

**Comment by MartinFlischman** [comment]
I managed to get it working, but after multiple crashes of elementary OS, I installed pop!_OS. Waiting for Odin to possibly move back.
